/**
 * setup.js - Auto-decrypt Trae CN config and save to .env
 *
 * Usage: node setup.js
 */

const fs = require('fs');
const path = require('path');
const { decryptAuthData, getTraeCNDataDir, getTraeSGDataDir } = require('./src/trae-decrypt');

const ENV_PATH = path.join(__dirname, '.env');

console.log('');
console.log('╔══════════════════════════════════════════╗');
console.log('║    Trae Local API - Auto Setup           ║');
console.log('╚══════════════════════════════════════════╝');
console.log('');

// Try CN edition first, then SG
let authData = null;
let edition = 'cn';

try {
  console.log('[setup] Trying CN edition...');
  authData = decryptAuthData(getTraeCNDataDir());
  edition = 'cn';
  console.log('[setup] CN edition decrypt success');
} catch (e) {
  console.log(`[setup] CN edition failed: ${e.message}`);
  try {
    console.log('[setup] Trying SG edition...');
    authData = decryptAuthData(getTraeSGDataDir());
    edition = 'sg';
    console.log('[setup] SG edition read success');
  } catch (e2) {
    console.error(`[setup] SG edition failed: ${e2.message}`);
    console.error('');
    console.error('Failed to read Trae config. Ensure:');
    console.error('  1. Trae IDE is installed');
    console.error('  2. You are logged in to Trae');
    console.error(`  3. Config file exists at:`);
    console.error(`     CN: ${path.join(getTraeCNDataDir(), 'globalStorage', 'storage.json')}`);
    console.error(`     SG: ${path.join(getTraeSGDataDir(), 'globalStorage', 'storage.json')}`);
    process.exit(1);
  }
}

// Build .env content
const envContent = [
  '# Auto-generated by setup.js - do not edit manually',
  `# Generated at: ${new Date().toISOString()}`,
  '',
  '# Trae Edition',
  `TRAE_EDITION=${edition}`,
  '',
  '# Auth credentials (auto-decrypted from Trae)',
  `TRAE_TOKEN=${authData.token || ''}`,
  `TRAE_REFRESH_TOKEN=${authData.refreshToken || ''}`,
  `TRAE_USER_ID=${authData.userId || ''}`,
  `TRAE_API_HOST=${authData.host || (edition === 'cn' ? 'https://api.trae.cn' : 'https://api.trae.ai')}`,
  '',
  '# Token expiry info',
  `TRAE_TOKEN_EXPIRES=${authData.expiredAt || ''}`,
  `TRAE_REFRESH_EXPIRES=${authData.refreshExpiredAt || ''}`,
  '',
  '# Account info',
  `TRAE_USERNAME=${authData.account?.username || ''}`,
  `TRAE_REGION=${authData.userRegion?.region || edition.toUpperCase()}`,
  '',
  '# Server config',
  'API_KEY=trae-local-api',
  'PORT=19900',
  '',
].join('\n');

// Write .env
fs.writeFileSync(ENV_PATH, envContent, 'utf8');

console.log('');
console.log('=== Setup Complete ===');
console.log('');
console.log(`Edition:      ${edition.toUpperCase()}`);
console.log(`UserID:       ${authData.userId}`);
console.log(`Username:     ${authData.account?.username || 'N/A'}`);
console.log(`Region:       ${authData.userRegion?.region || 'N/A'}`);
console.log(`Token:        ${authData.token ? authData.token.substring(0, 40) + '...' : 'N/A'}`);
console.log(`Token Expiry: ${authData.expiredAt || 'N/A'}`);
console.log(`Refresh Expiry: ${authData.refreshExpiredAt || 'N/A'}`);
console.log('');
console.log(`Saved to: ${ENV_PATH}`);
console.log('');
console.log('Start the server with:');
console.log('  npm start');
console.log('');
